SELECT COUNT(*) FROM main WHERE UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(lts) > 2*90*24*3600;
SELECT COUNT(*) FROM inkas WHERE UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(lts) > 2*90*24*3600;
SELECT COUNT(*) FROM cmds WHERE UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(lts) > 2*90*24*3600;
SELECT COUNT(*) FROM cashier_inkass WHERE UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(lts) > 2*90*24*3600;
SELECT COUNT(*) FROM dayly_stats WHERE UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(lts) > 2*90*24*3600;
